# fly.toml app configuration file generated for grep-fuseki on 2026-03-13T12:40:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grep-fuseki'
primary_region = 'arn'

# Bygges via Dockerfile på GitHub

[env]
  FUSEKI_PASSWORD = 'admin'

[[mounts]]
  source = 'fuseki_storage_v3'
  destination = '/fuseki'
  initial_size = '10gb'

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '2gb'
  cpus = 1
