# fly.toml app configuration file for grep-fuseki-v3
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'grep-fuseki-v3'
primary_region = 'arn'

# Bygges via Dockerfile på GitHub

[env]
  FUSEKI_PASSWORD = '+01Raspeballer'
  TDB2_USE_MEMORY_SEGMENTS = 'false'

[[mounts]]
  source = 'fuseki_storage_v4'
  destination = '/fuseki'
  initial_size = '10gb'

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-2x'
  memory = '4gb'
