# fly.toml app configuration file generated for grep-fuseki on 2026-03-13T12:40:06+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'grep-fuseki'
primary_region = 'arn'

# Bygges via Dockerfile på GitHub

[env]
  FUSEKI_PASSWORD = 'admin'

[[mounts]]
  source = 'fuseki_data'
  destination = '/fuseki'

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3030

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
